### ISSUE TITLE
Production Rails secret shouldn't be the same as the test instances

### ISSUE THREAD

**Issue by quad** [markryall/floodhousing#34]
The production branch should have a new secret. Otherwise someone can just look at the public repo and access people's accommodation pages, smash cookies, and be a dick.

**Comment by markryall** [comment]
changed to try to load secret from an env variable

**Comment by quad** [comment]
Use http://ozfloodhelp.org/l/1/8ntuo83b8jjwcg508n3x7mker in a browser without cookies / in porn mode to test.

**Comment by markryall** [comment]
yep - needed to redeploy first
