### ISSUE TITLE
Double opt-in for email

### ISSUE THREAD

**Issue by kuperov** [markryall/floodhousing#40]
Users should have to confirm their email address in order to list their accommodation on the site.

Otherwise we risk all kinds of nasty, as explained by Scott H in the following chat transcript:

Rob H.  Scott Robinson: And it's necessary for unspamminess?
Scott R.    Otherwise, you'll get listed in five seconds.
Rob H.  i mean it's a good idea, no doubt
oh right
Scott R.    @Rob As in, if we get any traction
Rob H.  by spambots
Alex C. Without double opt in, we can go live and fix it as a first incremental change.
Scott R.    then rbls and spam bots and everyone else will check our site
Alex: No.
Alex: What happens is if you get traction
Alex: Which is to say, even a thousand e-mails to a few large domains
Alex: Then your site will be checked.
Alex: And if you aren't already COI, then you will be listed.
And it's fucking _hard_ to get unlisted.
And it takes from days to weeks.

_snip_

Group consensus ensued.

**Comment by markryall** [comment]
all i did was changed the initial state of the accommodation to be unavailable and slightly reworded the confirmation page and emails.

can we get rid of email confirmation now?
