### ISSUE TITLE
Move static assets off Heroku

### ISSUE THREAD

**Issue by kuperov** [markryall/floodhousing#44]
Static assets are currently being served from Heroku, over SSL.

This will be very, very slow, and require an inordinate number of workers. Heroku SSL is slow.

Suggest S3, Cloudfront or even better, an Australian CDN. Remember SSL must be supported.

**Comment by r5v9** [comment]
cachefly has some POPs in australia, but it's a little expensive. otherwise we could just use S3.

**Comment by pcalcado** [comment]
Phil C. i'm confused about #44.
isnt it just a matter of removing the https from statics?
heroku uses varnish already; we should be good just by using plain http

**Comment by markryall** [comment]
if the css, images, etc. were delivered over http wouldn't we reintroduce all the mixed content ssl warnings?
