### ISSUE TITLE
Email links incorrect

### ISSUE THREAD

**Issue by kuperov** [markryall/floodhousing#46]
Email links must point to the correct HTTPS address on the site.

Otherwise they will NOT work once the secure redirect is in place.

NB: you will probably not be able to reproduce this on staging.

**Comment by kuperov** [comment]
It turns out these links are causing the spam rating. (Found by Francois.)

**Comment by markryall** [comment]
the link to edit your listing is now correct - contains https

how's this go with the spam rating?

**Comment by quad** [comment]
Fixed in production. We do have an issue in that ozfloodhelp.org is a young domain and thus is pulling us some spam rank. However, that'll go away only with time.
