### ISSUE TITLE
we need a headless, always-online build server

### ISSUE THREAD

**Issue by strongcoffee** [markryall/floodhousing#57]
1. grab the hudson of mark
2. chuck it on a server somewhere
3. figure out how to make firefox start without a display 
4. leave it running and posting to campfire

**Comment by starapor** [comment]
One option is to use teamcity on the codebetter website (http://codebetter.com/jameskovacs/2009/02/24/announcing-teamcity-codebetter-com/)

Or - see if studios can provide us with a free hosted version of GO
