### ISSUE TITLE
prod email went to spam, and has wrong link

### ISSUE THREAD

**Issue by strongcoffee** [markryall/floodhousing#58]
I accidentally created a listing in prod and noticed email went to spam, and it contains the wrong link (ignore the indonesian - thats from my gmail)

dari    OzFloodHelp ozfloodhelp@getup.org.au
ke  my_email
tanggal 19 Januari 2011 02.32
subjek  Please confirm your offer of help
dikirim oleh    blast.getup.org.au
Ditandatangani oleh getup.org.au
perlihatkan detail 02.32 (20 menit yang lalu)
Thank you for volunteering to provide someone with a home in a time of
need.

Your offer has not been listed on www.ozfloodhelp.org quite yet.

Please confirm your listing by following this link and clicking 'post my offer on the website, please':

 http://www.ozfloodhelp.org.au/l/93/36g6dr1euszq279i7tc1tf1cg  --> wrong domain

Next steps

**Comment by strongcoffee** [comment]
it's the reincarnte of issue 46.  its in preprod , except you can only test it in prod.  its a small code change - could do  a code review - and i didn't want to push to prod this late. create a test listing , u dont have to publish it, and see if you get the email ok.

**Comment by quad** [comment]
I checked it out and released it.
