### ISSUE TITLE
a way to find out how many people have not confirmed their listing

### ISSUE THREAD

**Issue by strongcoffee** [markryall/floodhousing#64]
given the problems with email, we need a basic way to track unconfirmed listings (a json file with counts?) to see if the problem is continuing.

**Comment by gga** [comment]
I've added a task to count this. Once you've promoted, run:

heroku rake floods:report:unconfirmed_listings

**Comment by markryall** [comment]
this current implementation (using created_at = updated_at to work out whether a listing has never been activated) won't quite work any more - many of the updated_at fields were modified to get around the problem where contact_count was null.

We'll need to change to a more sensible model where either we have a state field (new, active, taken) or make use of the 'enabled' boolean which current doesn't seem to serve any purpose.

**Comment by markryall** [comment]
the state based implementation would make more sense but given the enabled flag is already there i changed the create action to initially set enabled to false and the update action to always set it to true.

listings that have never been activated (created after this deployment) will have enabled = false.

**Comment by markryall** [comment]
i changed the rake task too - it now uses not available and not enabled as criteria to identify listings that haven't yet been activated.

Note that this will give misleading results for a while since enabled is true on all existing production records - we could consider resetting enabled to false
