### ISSUE TITLE
people should only have to click on the link to publish listing 

### ISSUE THREAD

**Issue by strongcoffee** [markryall/floodhousing#71]
Check with Sam - but I think there is a usability issue that they have to click on the link and then "Please publish"  - was there a reason we did it like that?

**Comment by FrancoisChemillier** [comment]
Sam confirmed to me that we need to cahnge the process so that, upon clicking on the link within the conformation email it will automatically publish the offer (and takes you to the same page where you can edit the offer and unpublish it)

**Comment by markryall** [comment]
it looks to me like julio successfully implemented this today - i tested it while looking into the problem of distinguishing listings that have been marked as available from those that have never been published

**Comment by FrancoisChemillier** [comment]
hey Mark,
I did make the changes today. Sorry, I forgot to close it.
