### ISSUE TITLE
Problem recording number of beds available (reported issue)

### ISSUE THREAD

**Issue by kuperov** [markryall/floodhousing#73]
On Fri, Jan 21, 2011 at 1:44 PM, Aidan G wrote:
Hi Alex,

Having a few of the volunteers reporting a minor glitch on the website. When they attempt to key in the number of available beds from the drop down menu, it won't actually register the amount. To get around it they have been first keying in whether the space is pet friendly or not then going back.

Aidan

**Comment by kuperov** [comment]
Further details from Aidan:
- picking a number of beds doesn't trigger a search.
- picking a number of beds then picking another search criterion _does_ trigger a search

**Comment by strongcoffee** [comment]
what browsers are they using?

**Comment by pcalcado** [comment]
Confirmed on chrome/mac
