### ISSUE TITLE
why do we have so many unconfirmed listings?

### ISSUE THREAD

**Issue by strongcoffee** [markryall/floodhousing#75]
stats at the moment show 268/732 (unconfirmed / total listings) . this number seems high. are people changing their minds about publishing their listing? or is our process for posting a listing a bit broken? eg. emails could be going to spam, or people don't realise they have to click on a link.

although the unconfirmed listings is probably not the bottleneck of our system given that we may not have a high demand of seekers (would be good to quantify seekers), it is still worth investigating this aspect of our application to assess its effectiveness.

today we deployed a change so now instead of clicking a link from the email and then another link saying "publish my listing", the host just has to click on the link in the email to publish their listing. we expect this to increase ratio of published listings.

another idea is to send a reminder email to people and see if this results in more published listings, which would suggest the previous process was broken. we can track the number of people that click on the link from the reminder email.

we also now have an admin page to browse and publish unconfirmed listings. the problem with this is that those people may not have the links to edit/delist their listing, and there may be people there that actually don't want to publish.

plan - track how many people are not confirming by
1. tracking  number of hits on the thank you page
2. tracking number of hits on the confirm link from the confirmation email

and  send a reminder email and track the number of hits from the reminder email

it may also be useful to ask users for feedback on the process.

**Comment by pcalcado** [comment]
I've added google analytics even tracking for confirmation. in 24h from deployment we should have data on this step so that we can correlate with number of submissions

build #165

**Comment by strongcoffee** [comment]
added a rake task (rake floods:confirmation_reminder_emai) to send a reminder email to ppl with unconfirmed listings - need sam to confirm the wording of the email

have tested running the rake task in preprod, it works.  email account i use is ozfloodhelptest@gmail.com, floods2011

**Comment by strongcoffee** [comment]
to run the rake task to run the email against production, run following command locally

heroku rake floods:confirmation_reminder_email --app ozfloodhelp
