### ISSUE TITLE
Ozfloods email getting marked as spam

### ISSUE THREAD

**Issue by markryall** [markryall/floodhousing#9]

**Comment by kuperov** [comment]
Confirmed on a 2-week-old account, kelseylgrantham@gmail.com, 19:20 on 17/1/11.

Suggest:
- use "Dear Alex," in the top line
- plaintext, not HTML
- proper signoff
- turn off click tracking

Currently investigating whether we can use the current sendgrid account in plaintext mode.

**Comment by kuperov** [comment]
All of these changes have been made. Gmail sometimes puts things as spam, sometimes not.

I now suspect the domain name itself. Going to try sending from another working account instead.

**Comment by kuperov** [comment]
Some success using a real name. "Flood" seems to be a spam keyword. Should we consider another domain???

**Comment by starapor** [comment]
When I used thoughtworks.com domain, the emails were being delivered to my gmail account.

**Comment by kuperov** [comment]
Seems like Google Apps is OK.

**Comment by kuperov** [comment]
Have been in contact with Google. They're looking into it.

**Comment by FrancoisChemillier** [comment]
Fixed, we've replaced the link into the email content from www.ozfloodhelp.org TO www.ozfloodhelp.org.au and it worked ...
